name: Bug report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear description of the bug + actual vs expected behaviour
    validations: { required: true }
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Upload demo SBOM
        2. Click on …
        3. Observe …
    validations: { required: true }
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: dev / prod / local docker-compose
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
